export PROMPT="%F{red}%n%f@%F{red}%M%f:%~$ "

source $HOME/.aliases
source $HOME/.exports

# up/down arrows to search through history, since zsh does not read inputrc
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search
